### ISSUE TITLE
Not working with current version of deployer

### ISSUE THREAD

**Issue by chrisvasey** [sourcebroker/deployer-extended-wordpress#10]
Hello, 

Love this package but currently having some issues getting it to work with the current version of deployer (6.4.3).

One example being the examples use server() and the current spec uses host().
After changing this I get other errors in the composer update command, can provide more logs info if needed.

Is this to de with versions or is it my local config?
If you need help updating I am happy to fix the errors I am seeing and make a pull request but thought I would check first to see if work has been started.

All the best

Thanks
Chris

**Comment by kszymukowicz** [comment]
Thats right. 

Current version of deployer-extended-wordpress is working only with deployer 4.3.x
This dependency is set in composer.json - line: "deployer/dist": "~4.3.1".

I do not have now time to upgrade it to deployer 6.x - I am not even sure I want. Deployer 4.3 has one advantage. Its still working with PHP 5.6 and PHP 7.x. Deployer 6.4 does not work with PHP 5.6.

Now please tell me what functionality you miss in Deployer 4.3 that you have in Deployer 6.4?
Maybe I miss something :)

**Comment by thinkstylestudio** [comment]
I too, am quite curious if there is any advantages?

**Comment by kszymukowicz** [comment]
The switch to Deployer 6 is planned on June/July 2019.

**Comment by kszymukowicz** [comment]
Version 1.0.0. is compatible with Deployer 6.x
Happy using :)
