### ISSUE TITLE
what will be the content of wp-config-local.php.dist file ??

### ISSUE THREAD

**Issue by MalikZohaib** [sourcebroker/deployer-extended-wordpress#6]

**Comment by MalikZohaib** [comment]
So we have to add database info manually in wp-config-local-php by going over ssh after first deploy on server? becasue it will not be in git right?

**Comment by kszymukowicz** [comment]
Yes. After first, usually failed, deploy you will have empty file "wp-config-local.php" in folder "shared". You can create that file also before first deploy if you like but I usually create that during first initial testing deploys.

**Comment by MalikZohaib** [comment]
ok great i have writtent a task to papulate this with db info on first deploy.. Thanks for the help..
