### ISSUE TITLE
wpdep db:pull live not working fine

### ISSUE THREAD

**Issue by MalikZohaib** [sourcebroker/deployer-extended-wordpress#8]
➤ Executing task db:pull

In functions.php line 365:

  The command "/usr/bin/wpdep db:export live --dumpcode=80321170f7000218563f6861f727b59e " failed.

  Exit Code: 1(General error)

  Working directory: /var/www/wpstructure-extended

  Output:
  ================
  ➤ Executing task db:export

  Error Output:
  ================

  In NativeSsh.php line 102:

    [RuntimeException]

**Comment by kszymukowicz** [comment]
plz give full output "dep db:pull live -vvv"

**Comment by kszymukowicz** [comment]
Yes. Deployer binary is in ./vendor/bin/dep. You should not used globally installed as the right verison of deployer is in ./vendor/bin/dep.

Try use "./vendor/bin/dep db:pull live"

**Comment by MalikZohaib** [comment]
Actually i have combined the ./vendor/bin/dep with the wordpress-extended-deployer and created a wpdep binary and i am using that to deploy in gitlab ci using docker container, Everything is working fine except this db:pull live task on local..
So its already using deployer binary it will not be an issue ?

**Comment by kszymukowicz** [comment]
Task to pull database needs that you ci has also connection to live instance. I am not sure how your env is looking like to help you more.

**Comment by kszymukowicz** [comment]
btw: what value of INSTANCE you have in wp-config-local.php on live instance?

**Comment by MalikZohaib** [comment]
Ok i changed the path but still i am getting above error.

**Comment by kszymukowicz** [comment]
Paste logs with new path.

**Comment by MalikZohaib** [comment]
Thanks it worked after changing path...
