### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by qurtopianodesign** [sourcebroker/deployer-extended-wordpress#9]
Hi,
when  I issue composer require deployer-extended-wordpress I get this error:

  Problem 1
    - Installation request for sourcebroker/deployer-extended-wordpress ^0.5.0 -> satisfiable by sourcebroker/deployer-extended-wordpress[0.5.0].
    - sourcebroker/deployer-extended-wordpress 0.5.0 requires sourcebroker/deployer-extended ^7.0.0 -> satisfiable by sourcebroker/deployer-extended[7.0.0, 7.1.0, 7.1.1, 7.1.2, 7.1.3] but these conflict with your requirements or minimum-stability.

**Comment by kszymukowicz** [comment]
Sry. I can not reproduce. Some more details?

**Comment by kl3sk** [comment]
@kszymukowicz  I think your `composer.json` is not up to date with the latest version of `deployer`, I had the same issues.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sourcebroker/deployer-extended-wordpress ^0.5.0 -> satisfiable by sourcebroker/deployer-extended-wordpress[0.5.0].
    - Conclusion: remove symfony/console v4.2.3
    - Conclusion: don't install symfony/console v4.2.3
    - sourcebroker/deployer-extended-wordpress 0.5.0 requires wp-cli/wp-cli ^1.2 -> satisfiable by wp-cli/wp-cli[v1.2.0, v1.2.1, v1.3.0, v1.4.0, v1.4.1, v1.5.0, v1.5.1].
    - wp-cli/wp-cli v1.2.0 requires symfony/console ^2.7|^3.0 -> satisfiable by symfony/console
```

**Comment by kszymukowicz** [comment]
@kl3sk
How you deploy.php files looks like ?

**Comment by kl3sk** [comment]
@kszymukowicz I cant give you this for now. But it is basic, it juste `init` it.
But I think it's due to composer version between your package and deployer package.

You allow deployer `v4.31` and the latest is `v6.4.3`. Where `symfony 4` packages version are allowed.

It is just an idea tell me if I'm wrong.

**Comment by kszymukowicz** [comment]
@kl3sk 

Why you need Deployer 6.4? How is it better than Deployer 4.3? Can you point some really nice features that you miss in Deployer 4.3? 

For me Deployer 4.3 has one big advantage - it works also with PHP 5.6.

**Comment by kl3sk** [comment]
@kszymukowicz 

Just because it is the lastest version. Your answer is acceptable, but I use anonymous function and PHP 5.6 doesn't (for example).
And why not use PHP 7.x now ?

A solution may be have to different packages. One for PHP 5.6 and an other for PHP 7.x no ?

**Comment by kszymukowicz** [comment]
@kl3sk 
I have yet some legacy projects with PHP 5.6 and I do not have time to support two different packages of deployer-extended-wordpress (one for PHP 5.6 and an other for PHP 7.x)

If there will be really some nice features in new version of Deployer then I will consider to switch to Deployer 6.4.

**Comment by kl3sk** [comment]
@kszymukowicz Ok I understand your approach, but It doesn't works with PHP 7.x out of the box.
With some adjustment it could be compatible with both I think.

You should even add it to your ReadMe.
In fact, this package look quite interesting, but without PHP 7.x support, it looks less.

**Comment by kszymukowicz** [comment]
@kl3sk
What exactly does not work for deployer-extended-wordpress and php 7.x ?

**Comment by kl3sk** [comment]
@kszymukowicz I simply cant install it, see my first message.

I think (again) because of SF4 packages.

**Comment by kszymukowicz** [comment]
@kl3sk 
I use that with PHP 7.1 without any problems.

**Comment by kl3sk** [comment]
Did you use the latest version of deployer too ?

**Comment by kszymukowicz** [comment]
No. I told you already that deployer-extended-typo3 is compatibile only with Deployer 4.3.
But you can use PHP 7.x with Deployer 4.3. without any problems.

**Comment by kl3sk** [comment]
Ok, so it is totally not compatible with the last version of deployer.
